#!/bin/bash

# Script to update the album cover art of all songs in a directory
if [[ -z $1 ]]; then
    echo "Album art file is required.
Usage:
$ update-FLAC-cover-art cover.jpg "
exit 1

fi 

for f in *; do

if [[ "$f" == *.jpg ]]; then
	continue
else

metaflac --import-picture-from="$1" "$f"

fi
done