#!/bin/bash

# Script to update the artist and album of all songs in a directory

if [[ -z $1 && -z $2 ]]; then
    echo "Artist and Album is required.
Usage:
$ update-artist 'Etta James' 'The Definitive Collection'"
exit 1

fi

for f in *; do

ffmpeg -i "$f" -c copy -metadata artist="$1" -metadata album_artist="$1" -metadata album="$2" 2-"$f"

done