#!/bin/bash

# Script to update the album of all songs in a directory

if [[ -z $1 ]]; then
    echo "Album is required.
Usage:
$ update-album 'Moondance' "
exit 1

fi

for f in *; do

ffmpeg -i "$f" -c copy -metadata album="$1" 2-"$f"

done