#!/bin/bash

# Script to update the album cover art of all songs in a directory

for f in *; do

if [[ "$f" == *.jpg ]]; then
	continue
else
	ffmpeg -i "$f" -i "$1" -c copy -map 0 -map 1 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (Front)" 2-"$f"
fi
done